import sys, json
sys.path.insert(0, '.')
from dotenv import load_dotenv
load_dotenv()

from agent.parquet_agent import ParquetQueryAgent

agent = ParquetQueryAgent()
result = agent.run_query("regional revenue", user_id="admin")

print("\n" + "="*80)
print("COMPLETE AGENT RESPONSE STRUCTURE")
print("="*80)

def print_structure(obj, indent=0, max_depth=4):
    """Print nested structure with type info"""
    prefix = "  " * indent
    
    if indent > max_depth:
        print(f"{prefix}...")
        return
    
    if isinstance(obj, dict):
        for key, value in obj.items():
            if isinstance(value, (dict, list)):
                value_type = type(value).__name__
                length = len(value) if isinstance(value, (list, dict)) else 0
                print(f"{prefix}├─ {key}: {value_type} ({length} items)")
                print_structure(value, indent + 1, max_depth)
            else:
                value_preview = str(value)[:60] if value else "None"
                print(f"{prefix}├─ {key}: {type(value).__name__} = {value_preview}")
    elif isinstance(obj, list):
        for i, item in enumerate(obj[:3]):  # Show first 3 items
            if isinstance(item, (dict, list)):
                print(f"{prefix}[{i}]: {type(item).__name__}")
                print_structure(item, indent + 1, max_depth)
            else:
                print(f"{prefix}[{i}]: {type(item).__name__} = {str(item)[:60]}")
        if len(obj) > 3:
            print(f"{prefix}... and {len(obj) - 3} more items")

print_structure(result)

print("\n" + "="*80)
print("KEY SECTIONS EXPLAINED")
print("="*80)

sections = {
    "user_input": "The original query from user",
    "session_id": "Unique ID for this conversation",
    "user_id": "User who made the query",
    "timestamp": "When the query started",
    "control": "Final state (end/wait_for_user/etc)",
    "last_node": "Last node executed (end)",
    
    "plan": "SQL plan generated by LLM",
    "plan_quality": "Confidence level (high/medium/low)",
    "plan_explain": "LLM's explanation of the plan",
    
    "execution_result": "Raw query results from DuckDB",
    "execution_stats": "Performance metrics",
    
    "satisfaction": "LLM's quality assessment",
    "evaluator_notes": "LLM's evaluation reasoning",
    
    "conversation_history": "Last 5 interactions (short-term memory)",
    
    "final_output": {
        "response": "User-friendly answer",
        "prompt_monitor": "Full debugging details"
    },
    
    "logs": "Step-by-step execution log",
    "metrics": "Performance timings"
}

for key, desc in sections.items():
    if isinstance(desc, dict):
        print(f"\n📦 {key}:")
        for subkey, subdesc in desc.items():
            print(f"   ├─ {subkey}: {subdesc}")
    else:
        print(f"📦 {key}: {desc}")

